name: flutterjdshop
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #  font_awesome_flutter: ^10.4.0
  #多语言和时间
  flutter_localizations:
    sdk: flutter
  intl: any
  #
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1

  #网络请求
  retrofit: ^4.0.1
  dio: ^5.0.0
  logger: ^1.1.0
  #路由相关
  go_router: ^6.0.10

  #数据存储
  hive_flutter: ^1.1.0

  #加载图片
  cached_network_image: ^3.2.3

  tuple: ^2.0.1

  #权限管理
  permission_handler: ^10.2.0
  #弹窗
  flutter_smart_dialog: ^4.8.2+5

  #扩展布局
  flextras: ^1.0.0

  url_launcher: ^6.1.10
  webview_flutter: ^4.0.5
  equatable: ^2.0.5
  #工具
  quiver: ^3.2.1

  #  flutter_secure_storage: ^8.0.0
  dropdown_button2: ^2.0.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_animate: ^4.1.0
  decimal: ^2.3.2
  #生成二维码
  qr_flutter: ^4.0.0
  #扫一扫二维码
  qr_code_scanner: ^1.0.1
  #  secp256k1: ^0.3.0
  #  dart_multihash: ^0.0.1
  #  base32: 2.1.3
  local_auth: ^2.1.6
  flutter_screen_lock: ^9.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.0.1
  riverpod_generator: ^1.2.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  hive_generator: ^2.0.0
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.3.1
  #生成资源文件
  flutter_gen_runner: ^5.2.0
  json_annotation: ^4.8.0
  pigeon: ^9.0.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/data/


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml
